# Generated by Django 5.1.2 on 2025-01-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='people',
            new_name='guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
