# Generated by Django 5.1.2 on 2025-01-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_date_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
