# Generated by Django 5.1.2 on 2025-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fb_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
