# Generated by Django 5.1.2 on 2025-01-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_fb_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_no',
        ),
    ]
