# Generated by Django 5.1.2 on 2025-01-10 01:40

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=bookings.models.current_time_utc_plus_8),
        ),
    ]
