# Generated by Django 5.1.2 on 2025-01-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
