# Generated by Django 5.1.2 on 2025-01-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='accepted',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
